### ISSUE TITLE
Not able to install using documentation

### ISSUE THREAD

**Issue by nicomen** [domeneshop/certbot-dns-domeneshop#3]
```
$ pip install certbot-dns-domeneshop
Collecting certbot-dns-domeneshop
  Could not find a version that satisfies the requirement certbot-dns-domeneshop (from versions: )
No matching distribution found for certbot-dns-domeneshop
```

(trying pip3 install … works as sudo but certbot-auto does not find the module, pip3 install … as regular user ends up with core dump)

**Comment by nicomen** [comment]
Ok, this is weird, probably PEBCAK. But no idea what may cause this:

```
$ pip search certbot-dns | grep domeneshop
certbot-dns-domeneshop (0.2.8)           - Domeneshop Certbot Plugin

$ pip install certbot-dns-domeneshop
Collecting certbot-dns-domeneshop
  Could not find a version that satisfies the requirement certbot-dns-domeneshop (from versions: )
No matching distribution found for certbot-dns-domeneshop
```

**Comment by nicomen** [comment]
Ok, this helped, guess I need to follow the python > 3.3 path then…

```
$ pip install certbot-dns-domeneshop==0.2.8 --verbose
Collecting certbot-dns-domeneshop==0.2.8
  1 location(s) to search for versions of certbot-dns-domeneshop:
  * https://pypi.python.org/simple/certbot-dns-domeneshop/
  Getting page https://pypi.python.org/simple/certbot-dns-domeneshop/
  Looking up "https://pypi.python.org/simple/certbot-dns-domeneshop/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/certbot-dns-domeneshop/" in the cache
  Current age based on date: 15
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 15
  Analyzing links from page https://pypi.org/simple/certbot-dns-domeneshop/
    The package https://files.pythonhosted.org/packages/c9/13/0efea0e54717da8d4f8a7e06064d32ae450e7fe67f338305dc1758ab3a96/certbot-dns-domeneshop-0.2.5.tar.gz#sha256=d0a5b2819e92bd2f964f9e22bae764a62d785056f575206fe7da43e7e8064862 (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/35/89/e50fb6240d5f3a69a7a28c06174878e5b9901ddb531f6d40d3d2cfa55453/certbot_dns_domeneshop-0.2.5-py2.py3-none-any.whl#sha256=fef1fbd2ce2bc0d46b2cc8706511ecbfa1ca4c1e7ab250987ce901cbc0361c87 (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/91/37/e7213129d407b8efe5790de4fc94f82e5cec2eeb1eeda8ba1045243a348f/certbot-dns-domeneshop-0.2.5.post1.tar.gz#sha256=6a3bd0f8dde32d31f0294fb337c521f208087fc5f58b1e85280e6418ff7ba1b4 (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/ba/98/5e072bb93e20fe048912181b838dc2a2805c61b48dfb9b9e4a22ef693b12/certbot_dns_domeneshop-0.2.5.post1-py2.py3-none-any.whl#sha256=d9879cffbc2be3e3efdfe2ec468df73cf146ba7fe8dd7d5124c581a93f71df39 (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/df/e7/44853ea2d342233f109a3145c4b70efed15555fd10423ad40e628344ffd0/certbot-dns-domeneshop-0.2.6.tar.gz#sha256=9b15396ee0b7c60c8ff44a1b1f0f68f82764f99ab66f4d75c5a8e64975b32be8 (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/a3/ee/b731069f7682dd2b4f16a3e3d87b00435175414ef232e7d5031de4c23c44/certbot_dns_domeneshop-0.2.6-py2.py3-none-any.whl#sha256=c48d5b0e2a5c168dfcb20a568db52168055c59d0c6277d7ab83c02dfc4df4cbc (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/3f/61/381e6356e36a513eac0854486c49c1e7b5b4ce2124f169cdd1020d079275/certbot-dns-domeneshop-0.2.7.tar.gz#sha256=15265542969176de4b08ca61bb7e57783cb570d30e02ce05b8b0bb9b54f75b1e (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/8a/ff/f3f779413ad26522cf3c341af730df1fc6535a62a703cf0e5e83e11eb2a1/certbot_dns_domeneshop-0.2.7-py2.py3-none-any.whl#sha256=d77ff42eb4bee8d63f8de188b499f31c5575ea8700baa13c01e6ad853d346a0c (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/78/4c/cf16c0b2bfa1650ada80c72db3592d91286b420395cbfd44617f6510bb22/certbot-dns-domeneshop-0.2.8.tar.gz#sha256=0f44e7920dc5d434b222588723582f6ad9c35b9f8c5a4bf3e9be9833e9d7a7f5 (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
    The package https://files.pythonhosted.org/packages/4f/8b/c4445ba30f6e8c7162fdf60db9b1dec7b43626cc185bf740b0f31fba0f29/certbot_dns_domeneshop-0.2.8-py2.py3-none-any.whl#sha256=1e46e7e1d690b5bf549fd1887152ae0152c3eb8b8a70a49e4d0fae04a9bf4d50 (from https://pypi.org/simple/certbot-dns-domeneshop/) (requires-python:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*) is incompatible with the pythonversion in use. Acceptable python versions are:!=2.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
  Could not find a version that satisfies the requirement certbot-dns-domeneshop==0.2.8 (from versions: )
Cleaning up...
No matching distribution found for certbot-dns-domeneshop==0.2.8
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for certbot-dns-domeneshop==0.2.8
```

**Comment by nicomen** [comment]
Even after forcing certbot-auto to use python3 via:
```
sudo apt install python3-venv     # Needed to install this or else certbot-auto crashed: (subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'venv', '/opt/eff.org/certbot/venv']' returned non-zero exit status 1.)
sudo rm -rf /opt/eff.org/certbot     # remove previous installation
USE_PYTHON_3=1 certbot-auto # reinstall
```
it doesn't find it.

[…some time later…]

After investigating virtualenv/venv and installing the python3 certbot-dns-domeneshop seemingly inside certbot's virtualenv/venv it still doesn't find it.

[…even more time later…]

After yet another try by doing `/opt/eff.org/certbot/venv/bin/activate` and `pip3 install certbot-dns-domeneshop` (as root I think (as I had to switch user to investigate `/var/log/letsencrypt/letsencrypt.log`)) I finally found it in `/opt/eff.org/certbot/venv/lib/python3.6/site-packages/certbot_dns_domeneshop…`

Also it turns out my particular version of certbot-auto 1.9.0 doesn't like the unprefixed version of --authenticator parameter.

All of this is on Ubuntu bionic, I guess a lot of people still have python2.7 + python3.6 installed, I think a version of certbot-dns-certbot for python2 or some details in how to force installing certbot to use python3 would be useful for others to avoid painstaking python, pip, virtualenv debugging sessions.

**Comment by nicomen** [comment]
This seems to be a working approach if certbot-auto chose python2.x when installed on Ubuntu 18.04 (bionic)
```
sudo apt install python3-venv     # Needed to install this or else certbot-auto crashed: (subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'venv', '/opt/eff.org/certbot/venv']' returned non-zero exit status 1.)
sudo rm -rf /opt/eff.org/certbot     # remove previous installation
USE_PYTHON_3=1 certbot-auto # reinstall
sudo /opt/eff.org/certbot/venv/pip3 install certbot-dns-domeneshop
```

**Comment by eirikrye** [comment]
Hi,

Neither `python-domeneshop` nor `certbot-dns-domeneshop` supports Python 2.x. While the Python 3 features used are not really essential, any rewrite to support Python 2 - which has been retired since January 1st this year - will not be prioritized. Not supporting Python 2.x has been a deliberate choice.

The readme for this repository should probably clarify this, though.

We have no experience with `certbot-auto`, unfortunately. If `certbot-auto` creates its own virtualenv in `/opt/eff.org/certbot/venv`, then you would have to install certbot-dns-domeneshop into that virtualenv which is what you appear to have done in your last comment.

Is there any specific reason why you are not using the `certbot` package provided by Ubuntu instead?

Either of the following alternatives work fine in my testing on Ubuntu bionic.

Using the system-provided certbot package:

```
~# apt-get install certbot python3-pip
~# pip3 install certbot-dns-domeneshop
~# certbot plugins
[... snip ...]
* certbot-dns-domeneshop:dns-domeneshop
Description: Obtain certificates using a DNS TXT record (if you are using
Domeneshop for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-domeneshop =
certbot_dns_domeneshop.dns_domeneshop:Authenticator
```

Using pip3-installed certbot in virtualenv:

```
~# apt-get install python3-venv
~# python3 -m venv certbot
~# source certbot/bin/activate
(certbot) ~# pip3 install wheel certbot certbot-dns-domeneshop
(certbot) ~# certbot plugins
[... snip ...]
* dns-domeneshop
Description: Obtain certificates using a DNS TXT record (if you are using
Domeneshop for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-domeneshop =
certbot_dns_domeneshop.dns_domeneshop:Authenticator

**Comment by eirikrye** [comment]
> Also it turns out my particular version of certbot-auto 1.9.0 doesn't like the unprefixed version of --authenticator parameter.

certbot should allow both the prefixed and unprefixed plugin parameters since certbot 1.7.0. See #2 for more information.

**Comment by eirikrye** [comment]
Using third-party plugins with `certbot-auto` is apparently not officially supported according to the documentation:

https://certbot.eff.org/docs/contributing.html

> Users who run certbot-auto are currently unable to use third-party plugins. It’s technically possible to install third-party plugins into the virtualenv used by certbot-auto, but they will be wiped away when certbot-auto upgrades.

I would suggest installing `certbot` and `certbot-dns-domeneshop` into a virtualenv using pip3, instead of using `certbot-auto`.

**Comment by nicomen** [comment]
Thanks for your feedback.

Will look into certbot. I see certbot-auto is being phased out, but at the time we installed it, it was supposed to be the preferred way to use certbot, oh well. The one provided by Ubuntu 18.04 itself is version 0.27.

I think adding a note about python3 dependency and therefore pip3 should be added to the docs, clarifying that certbot* running with python2 will not work. If you want you can probably add the workaround for certbot-auto, but perhaps there aren't many customers using that.

**Comment by eirikrye** [comment]
Since the certbot documentation states that plugins are not supported and will be wiped the next time `certbot-auto` upgrades, I don't think we should encourage that by adding the workaround to the documentation.

The certbot version provided by Ubuntu is indeed very old. I suggest using the version installed by pip3, either into the system's python environment directly, or using a virtualenv (the second example in my comment up there).
